title: Paul Berens
description: âœŒ
url: "https://berens.co"

collections:
  recipes:
    output: true
    permalink: /recipes/:path/
  prayers:
    output: true
    permalink: /prayers/:path/
  books:
    output: true
    permalink: /books/:path/
  runs:
    output: true
    permalink: /runs/:path/
  rides:
    output: true
    permalink: /rides/:path/


baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-github-metadata
  - jekyll-commonmark-ghpages
  - jekyll-gist